### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by valent** [k0dejunky/bitBot#1]
I have followed all the outlined steps but when i run the bot i get the following error
API ERROR OCCURRED at Fri Aug 25 09:27:53 2017
Message: INVALID_SIGNATURE 
 Sig Length: 38
Key Length: 32
|-- API ERROR Logged To File!
Can't open perl script "gimmeBitcoinzz.sh": No such file or directory

I am missing sign.php and gimmeBitcoinzz.sh though. Kindly advice.

**Comment by k0dejunky** [comment]
sign.php isn't used anymore gimmeBitcoinzz.sh is the file used to launch the script. The sql file needs to be updated as my code is different form the branched repo. 

gimmeBitcoinzz.sh - perl geekerV2.pl dbpassword | tee /var/www/html/pl/tLog.log
create a table called payout with id (auto increment, primary key) data (current timestamp) payout (decimal(16,8))  total (decimal(16,8))

**Comment by k0dejunky** [comment]
did you put your bittrex.com api keys in the database? this script only interacts with bittrex.com

**Comment by valent** [comment]
I have the bittrex  keys in the database. Am missing the gimmeBitcoinzz.sh file, can you share? Going to make the said changes in the database.

**Comment by k0dejunky** [comment]
no i can not share my gimmeBitcoinzz.sh it has passwords in it. Have explained what is in it in the posts above.

gimmeBitcoinzz.sh -> perl geekerV2.pl dbpassword | tee /var/www/html/pl/tLog.log

so the file contains:

perl geekerV2.pl (your database password) | tee (your server web folder)/pl/tLog.log

**Comment by valent** [comment]
I think i missed that part of gimmeBitcoinzz.sh file,let me create one.Many thanks for your help. Will let you know how it goes.

**Comment by k0dejunky** [comment]
awesome let me know if anything else doesn't work. I'm more than happy to help you get it running. Check back often for updates to the code. I update it fairly often lately.

**Comment by valent** [comment]
Still having issues. Kindly drop me a mail options2015(at)gmail.com

**Comment by valent** [comment]
Got it working.The problem is the sign function.

**Comment by seouyx** [comment]
i have mod the sign function and created the payout table, but bot still not made any transaction after several hours running... also got this two values empty... 
Payout :
|--- Total Reserved Bitcoin:

**Comment by b0b5h4rp13** [comment]
Well the bot will load the coins that show up in your Bittrex balances into the currencies table when it runs through once. After that  you need to manually put a 1 in tradeMe and a 1 in priceCheck if you want it to check the prices on that coin or have it trade that coin.

**Comment by k0dejunky** [comment]
Thank you bobsharpie for answering. I am reviewing your changes and will merge them soon. Thank you

**Comment by k0dejunky** [comment]
Thanks to Bobsharpie this issue can be closed. sign.php is no longer used. Digest::SHA is now used. Closing the issue as fixed. Thank you Bobsharpie

**Comment by b0b5h4rp13** [comment]
Your welcome.
